version: '3.9'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/backend/
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env
    ports:
      - 5432:5432
  rasa:
    build:
      context: ./rasa
      dockerfile: Dockerfile
    ports:
      - 5005:5005
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    volumes:
      - ./bot/:/bot/
    depends_on:
      - rasa
      - backend
    env_file:
      - ./bot/.env
volumes:
    postgres_data: