# Generated by Django 4.0.6 on 2022-08-08 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='Пользователь')),
                ('action', models.CharField(max_length=100, verbose_name='Тип действия')),
                ('content', models.CharField(max_length=100, verbose_name='Содержание')),
            ],
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(max_length=100, verbose_name='Интент')),
                ('examples', models.TextField(verbose_name='Примеры')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('intent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='responses.intent', verbose_name='Интент')),
                ('response_ru', models.TextField(verbose_name='Ответ(RU)')),
                ('response_en', models.TextField(verbose_name='Ответ(EN)')),
            ],
        ),
    ]
