# Generated by Django 4.0.6 on 2022-08-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0002_chatlog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intent',
            name='examples',
            field=models.TextField(blank=True, verbose_name='Примеры'),
        ),
    ]
