# Generated by Django 4.0.6 on 2022-08-08 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_id', models.CharField(max_length=100, unique=True, verbose_name='Telegram ID')),
                ('telegram_username', models.CharField(max_length=100, verbose_name='Telegram Username')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('timezone', models.CharField(blank=True, max_length=100, verbose_name='Часовой пояс')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_student', models.BooleanField(default=False, verbose_name='Ученик')),
                ('is_teacher', models.BooleanField(default=False, verbose_name='Учитель')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Админ')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Владелец')),
            ],
            options={
                'verbose_name_plural': 'Accounts',
                'ordering': ('-created_at', '-updated_at'),
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.CharField(default='admin', editable=False, max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Admins',
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.CharField(default='teacher', editable=False, max_length=7)),
                ('balance', models.IntegerField(default=0, verbose_name='Баланс')),
                ('is_senior', models.BooleanField(default=False, verbose_name='Старший')),
                ('working_time', models.JSONField(default=users.models.TeacherProfile.default_working_time, verbose_name='Рабочее время')),
            ],
            options={
                'verbose_name_plural': 'Teachers',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.CharField(default='student', editable=False, max_length=7)),
                ('last_call', models.DateTimeField(default='1900-01-01 12:00:00Z', verbose_name='Последний звонок')),
                ('call_duration', models.IntegerField(default=30, verbose_name='Длительность звонка')),
                ('teachers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.teacherprofile', verbose_name='Выбранные учителя')),
            ],
            options={
                'verbose_name_plural': 'Students',
                'ordering': ('last_call',),
            },
        ),
    ]
